# Generated by Django 5.2.17 on 2026-09-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_source',
            field=models.CharField(choices=[('MANUAL', 'Email and password'), ('GOOGLE', 'Google account')], default='MANUAL', max_length=10),
        ),
    ]
