# Generated by Django 5.2.17 on 2026-09-20 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('BUSY', 'Busy')], default='OFFLINE', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=80)),
                ('vehicle_plate', models.CharField(blank=True, default='', max_length=30)),
                ('license_number', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver profile',
                'verbose_name_plural': 'Driver profiles',
                'ordering': ('-created_at',),
            },
        ),
    ]
