# Generated by Django 5.2.17 on 2026-09-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='preferred_destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='preferred_pickup_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
