# Generated by Django 5.2.17 on 2026-09-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
