# Generated by Django 5.2.17 on 2026-09-20 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('payments', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='groups.group'),
        ),
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('TRIP', 'Trip'), ('GROUP_BUYOUT', 'Group buyout')], default='TRIP', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trips.trip'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('trip__isnull', False)), models.Q(('group__isnull', False), ('trip__isnull', True)), _connector='OR'), name='payment_has_one_target'),
        ),
    ]
