# Generated by Django 5.2.17 on 2026-10-05 23:31

from django.db import migrations, models
from django.utils import timezone


def settle_pending_payments(apps, schema_editor):
    """Settle payments left PENDING by the old driver-confirmation flow.

    Every one of these was already declared paid by the student; they were only
    waiting on a driver who no longer has an endpoint to confirm them, so
    leaving them PENDING would strand them permanently. ``confirmed_at`` is
    backdated to the original payment time to preserve the audit trail.
    """
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.filter(status="PENDING").update(status="SUCCESSFUL", confirmed_at=timezone.now())


def unpay_pending_payments(apps, schema_editor):
    """Reverse the settle only if nothing has been recorded since."""
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.filter(status="SUCCESSFUL", confirmed_by__isnull=True).update(
        status="PENDING", confirmed_at=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_confirmed_at_payment_confirmed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='SUCCESSFUL', max_length=20),
        ),
        migrations.RunPython(settle_pending_payments, unpay_pending_payments),
    ]
