# Generated by Django 5.2.17 on 2026-09-24 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_destination_lat_group_destination_lng_and_more'),
        ('trips', '0002_triprating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'driver'], name='trip_status_driver_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['created_by', '-created_at'], name='trip_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['pickup_location', 'destination'], name='trip_route_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('fare__gte', 0)), name='trip_fare_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_lat__isnull', True), models.Q(('pickup_lat__gte', -90), ('pickup_lat__lte', 90)), _connector='OR'), name='trip_pickup_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_lng__isnull', True), models.Q(('pickup_lng__gte', -180), ('pickup_lng__lte', 180)), _connector='OR'), name='trip_pickup_lng_range'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('destination_lat__isnull', True), models.Q(('destination_lat__gte', -90), ('destination_lat__lte', 90)), _connector='OR'), name='trip_destination_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('destination_lng__isnull', True), models.Q(('destination_lng__gte', -180), ('destination_lng__lte', 180)), _connector='OR'), name='trip_destination_lng_range'),
        ),
    ]
