# Generated by Django 5.2.17 on 2026-09-24 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmember_seat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='destination_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['pickup_location', 'destination'], name='group_route_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_by', '-created_at'], name='group_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'user'], name='group_member_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='group_capacity_min'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__lte', 12)), name='group_capacity_max'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_lat__isnull', True), models.Q(('pickup_lat__gte', -90), ('pickup_lat__lte', 90)), _connector='OR'), name='group_pickup_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_lng__isnull', True), models.Q(('pickup_lng__gte', -180), ('pickup_lng__lte', 180)), _connector='OR'), name='group_pickup_lng_range'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('destination_lat__isnull', True), models.Q(('destination_lat__gte', -90), ('destination_lat__lte', 90)), _connector='OR'), name='group_destination_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('destination_lng__isnull', True), models.Q(('destination_lng__gte', -180), ('destination_lng__lte', 180)), _connector='OR'), name='group_destination_lng_range'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.CheckConstraint(condition=models.Q(('seat__isnull', True), models.Q(('seat__gte', 1), ('seat__lte', 12)), _connector='OR'), name='group_member_seat_range'),
        ),
    ]
