# Generated by Django 5.2.17 on 2026-09-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_destination_lat_group_destination_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('FULL', 'Full')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
